name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
        with:
          source: "."
          target: "~/app"

      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: |
            # Set env variables
            export TG_API_KEY="${secrets.TG_API_KEY}"
            export POSTGRES_DB_CC="${secrets.POSTGRES_DB_CC}"
            export POSTGRES_USER_CC="${secrets.POSTGRES_USER_CC}"
            export POSTGRES_PASSWORD_CC="${secrets.POSTGRES_PASSWORD_CC}"
            export POSTGRES_DB_TB="${secrets.POSTGRES_DB_TB}"
            export POSTGRES_USER_TB="${secrets.POSTGRES_USER_TB}"
            export POSTGRES_PASSWORD_TB="${secrets.POSTGRES_PASSWORD_TB}"
            
            cd ~/app
            
            # build binaries
            make build
            
            # restart app
            docker-compose stop
            docker-compose rm -f
            docker-compose pull
            docker-compose up -d
            
            # migrate
            make migrate-up
